#include "Sttc.h"

#include "cutts_eglen_sttc.h"

using namespace System;
using namespace CuttsEglen;

double Sttc::Calculate(array<double>^ spikeTrain1, array<double>^ spikeTrain2, double startTime, double endTime, double dt) {
	// Make sure that both spike trains actually contain spikes
	if (spikeTrain1->Length == 0)
		throw gcnew DivideByZeroException("Spike train 1 does not contain any spikes!");
	if (spikeTrain2->Length == 0)
		throw gcnew DivideByZeroException("Spike train 2 does not contain any spikes!");

	// Do some manual marshalling
	double result;
	array<double>^ times = gcnew array<double>(2) { startTime, endTime };
	pin_ptr<double> timesPtr = &times[0];
	pin_ptr<double> trainPtr1 = &spikeTrain1[0];
	pin_ptr<double> trainPtr2 = &spikeTrain2[0];
	int n1 = spikeTrain1->Length;
	int n2 = spikeTrain2->Length;

	// Return the result generated by the external STTC function
	run_sttc(&n1, &n2, &dt, timesPtr, &result, trainPtr1, trainPtr2);
	return result;
}
